### ISSUE TITLE
AAP55 - aircrack-ng - Run test suite to verify operational

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#19]

**Comment by jolla** [comment]
Confirmed aircrack-ng suite was installed, version 1.5.2

Successfully tested the following aircrack-ng tools using a MediaTek MT76 Wi-Fi adapter
✅ airmon-ng
✅ airodump-ng
✅ aircrack-ng
✅ airbase-ng
✅ aireplay-ng
✅ airserv-ng
✅ airventriloquist-ng
