### ISSUE TITLE
AAP80 - ser2net - Add to base image build process

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#25]
Used by wconsole. Config file: /etc/ser2net.conf

1. systemctl on install
2. Svc: ser2net.service

**Comment by danielmundi** [comment]
Installed on base build.

So far it has only the default ser2net.conf file.

I believe the custom configuration comes from other packages like wconsole that change it dynamically, is that correct @wifinigel ?

**Comment by wifinigel** [comment]
@danielmundi  Yes, that is correct. When wconsole is selected from fpms, a bash script sets up a number of symbolic links to the required config files for hostapd and ser2conf. The default config for ser2net s fine for the image build.

**Comment by danielmundi** [comment]
Great, closing this.
