### ISSUE TITLE
AAP90 - apache - Verify present in image & update with apt update

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#27]
After package installation, some customization of the Apache config may be required to accommodate the new web gui requirements

1. systemctl on install
2. Svc: apache2.service

**Comment by danielmundi** [comment]
apache2 installed on base image.

@wifinigel Do you want to perform any other configuration here or should we have another task for that?

**Comment by wifinigel** [comment]
@danielmundi I'm not sure of the requirements around configuration (if any) as yet. I'll create another task as a placeholder for the task if it is required later.

**Comment by danielmundi** [comment]
Ok, closing this one then.
