### ISSUE TITLE
TPP00 - wifiexplorer-sensor - Add to base image build process

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#29]
1. During image build, package needs to be pulled in from GitHub repo, Debianized and then installed. 
2. Systemctl scripts need to be created and installed to allow on-demand start/stop of application from FPMS/web gui/Cockpit

Requires Python venv

**Comment by wifinigel** [comment]
Instructions for this can be found in this repo from @adriangranados : https://github.com/adriangranados/wifiexplorer-sensor

@danielmundi may be worth checking with @adriangranados that this is the current info

**Comment by adriangranados** [comment]
That's the current info. The sensor script should work with Python 3. Scapy is the only dependency. In the repo you can find the System V startup script. We would need to write a systemctl startup script.

**Comment by adriangranados** [comment]
I created the systemd startup script (see scripts/wifiexplorer-sensor.service in sensor's repo). I also tested the latest version of the sensor script and it's working fine.

@danielmundi What else is needed to "debianize" and install the sensor in the base image?

**Comment by adriangranados** [comment]
By the way, the new repo URL is [https://github.com/intuitibits/wifiexplorer-sensor](https://github.com/intuitibits/wifiexplorer-sensor)

**Comment by adriangranados** [comment]
@danielmundi has taken care of this. I tested it and the service loads fine, sensor is available for scanning provided an adapter is connected.
