### ISSUE TITLE
TPP03 - wifiexplorer-sensor - Create systemctl scripts for start on boot & manual startup/shutdown of server process

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#30]
1. During image build, package needs to be pulled in from GitHub repo, Debianized and then installed. 
2. Systemctl scripts need to be created and installed to allow on-demand start/stop of application from FPMS/web gui/Cockpit

**Comment by adriangranados** [comment]
This is done. Closing.
