### ISSUE TITLE
PHP06 - fpms - Run test suite to verify operational

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#42]

**Comment by jiribrejcha** [comment]
All menu items tested successfully with these caveats:
- Public IP address: output does not scroll down, refreshes too often and sometimes fails displaying the output, one for me to pick up
- Wiperf mode: switching not working "Switch failed: wiperf", @wifinigel is this expected (I have not applied any wiperf config or other changes)?
- Profiler: when you start it it gets stuck at "Info: Please wait..." and does not enable Profiler, no way to exit this screen, no SSID is broadcast, @joshschmelzle could you look into this please?

**Comment by jiribrejcha** [comment]
**Fixed and did PR to FPMS dev**
Public IP address: output does not scroll down, refreshes too often and sometimes fails displaying the output, one for me to pick up

**Comment by joshschmelzle** [comment]
I will take a look later tonight after my day job.

**Comment by jiribrejcha** [comment]
@joshschmelzle there is no /etc/profiler2 folder on my test Pi.

My image was built before the merge of this code to builder:
copy_overlay /etc/profiler2/config.ini -o root -g root -m 644

Building a fresh one and will re-test.

**Comment by joshschmelzle** [comment]
@jiribrejcha i am guessing `copy_overlay /etc/profiler2/config.ini -o root -g root -m 644` must be failing if the destination does not exist. i think we may need to add `mkdir /etc/profiler2` if `copy_overlay` does not handle creating the folder for us.

**Comment by jiribrejcha** [comment]
@joshschmelzle Profiler is now working, no changes needed. Sorry for bothering you. The latest PR fixed it and the config file is there in /etc/profiler2/config.ini:

![image](https://user-images.githubusercontent.com/18701525/90686701-a4a2e500-e263-11ea-9e94-80584f29261e.png)

**Comment by joshschmelzle** [comment]
Awesome!
