### ISSUE TITLE
PHP20 - wlanpi-topping - Add to base image build process (inc debian pkg creation, apache config & venv?)

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#46]

**Comment by danielmundi** [comment]
@wifinigel Which project is this?

**Comment by wifinigel** [comment]
This was part of the original web-GUI plans, by this is now shelved and will be replaced by the efforts around Cockpit.

**Comment by joshschmelzle** [comment]
Looks like this was addressed in https://github.com/danielmundi/build/commit/edaff5c1a34789a552920bb250e33635399bed66#diff-92c49b959fb47e632d4c0150b4e770c9 --- I think this can be moved to Done.
