### ISSUE TITLE
PHP35 - wlanpihotspot - Run test suite to verify operational (inc mode switch)

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#49]

**Comment by wifinigel** [comment]
Tested to ensure can join default SSID with default PSK & can route to Eth port OK.

**Comment by wifinigel** [comment]
interfaces file update & re-test req.

**Comment by jiribrejcha** [comment]
File updated and re-tested. Working fine after the change. Did PR to v2_image.

**Comment by jiribrejcha** [comment]
Built new dev image and successfully re-tested.
