### ISSUE TITLE
PHP40 - wconsole - Add to base image build process

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#50]
1. During image build, package needs to be pulled in from GitHub repo, Debianized and then installed. 
2. Mode switch method for v2.0.0 needs to be agreed - same as v1.x image?

**Comment by wifinigel** [comment]
wconsole files now available in wconsole dev branch.

Note that NetworkManager had to be disabled at start up to prevent interfering with operation of the wlan0 interface during startup. wlan0 would not come up with NetworkManager enabled.

To install wconsole:

1. copy repo filed to /etc/wconsole
2. move "/etc/wconsole/wconsole_switcher" to "/usr/bin/wconsole_switcher" & chmod 775.

cc: @danielmundi

**Comment by danielmundi** [comment]
This is included in the image, need to confirm if there is any other configuration to be made.

**Comment by wifinigel** [comment]
Config files all look good in image - closing
