### ISSUE TITLE
PHP45 - wconsole - Run test suite to verify operational (inc mode switch)

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#51]

**Comment by wifinigel** [comment]
Tests completed with Armbian_20.08.0-trunk_Wlanpi-neo2_buster_current_5.4.49.img.gz:

Test rig:
- Silver Neo2
- CF-912 NIC
- USB/Serial cable 
- Cisco 3560-CX switch serial console

1.  Switched from classic mode to wconsole using fpms - reboot took 43 secs 
2. fpms display shows wiperf mode OK and IP address of 192.168.42.1 on wlan0
3. SSID "wifi_console" detected OK from Windows laptop
4. Wi-Fi scanner shows SSID is AES/PSK on channel 1
5. Joined SSID with Windows laptop.
6. Performed telnet session to 192.168.42.1: 9600 and obtained serial port access to switch
7. Able to peform CLI commands as expected
![term](https://user-images.githubusercontent.com/19818404/86403221-313e1780-bca5-11ea-8ce0-2c166d73a86e.png)

8. Selected classic mode from FPMS. Time to boot back to classic mode: 47secs

**Comment by wifinigel** [comment]
interfaces file update & re-test req.

**Comment by jiribrejcha** [comment]
File updated and re-tested. Working fine after the change. Did PR to dev.

**Comment by jiribrejcha** [comment]
Built new dev image and successfully re-tested.
