### ISSUE TITLE
TPA20 - WinFi - Test WinFi on Windows machine can still access WLAN Pi as data source

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#58]

**Comment by wifinigel** [comment]
Test fails. Contacted Helge Keck and provided link to build image so that he can test.

**Comment by jolla** [comment]
Failed - attempted to use the WLAN Pi directly connected (169.254.42.1) and remotely using its IPv4 address. Both attempts resulted in "Interface not Ready"

**Comment by wifinigel** [comment]
@jolla Helge has a copy of the latest image to test & fix tis.

**Comment by wifinigel** [comment]
Helge has debugged and found issue with iw path change and tcpdump now needs sudo (not needed previously).  He will release a newversion of WinFi with a fix in the next couple of weeks.
