### ISSUE TITLE
AAP120 - TFTP - Add to base image build process

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#74]
Add ambian tftp server package to the image build

v1.9.1 process info:
```
/usr/sbin/in.tftpd --listen --user tftp --address 0.0.0.0:69 --secure /home/wlanpi/tftp/
```

systemctl output:
```
root@wlanpi:/home/wlanpi/tftp# systemctl  status tftpd-hpa.service
● tftpd-hpa.service - LSB: HPA's tftp server
   Loaded: loaded (/etc/init.d/tftpd-hpa; generated; vendor preset: enabled)
   Active: active (running) since Wed 2020-02-12 13:05:30 CST; 4min 43s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1430 ExecStart=/etc/init.d/tftpd-hpa start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/tftpd-hpa.service
           └─1508 /usr/sbin/in.tftpd --listen --user tftp --address 0.0.0.0:69 --secure /home/wlanpi/tftp/

Feb 12 13:05:29 wlanpi systemd[1]: Starting LSB: HPA's tftp server...
Feb 12 13:05:30 wlanpi tftpd-hpa[1430]: Starting HPA's tftpd: in.tftpd.
Feb 12 13:05:30 wlanpi systemd[1]: Started LSB: HPA's tftp server.
root@wlanpi:/home/wlanpi/tftp#                                                        
```

**Comment by danielmundi** [comment]
v1.9.1 also had this configuration:

```
$ cat /etc/default/tftpd-hpa
# /etc/default/tftpd-hpa

TFTP_USERNAME="tftp"
TFTP_DIRECTORY="/home/wlanpi/tftp/"
TFTP_ADDRESS="0.0.0.0:69"
TFTP_OPTIONS="--secure"
```

@jolla, @wifinigel,
Can we stick to the default location, which is `/srv/tftp` ?

**Comment by wifinigel** [comment]
Sorry, I couldn't find those config files....I was in a bit of  rush as it was late in the day here.

I'm not sure of the rationale of the original files location being /home/wlanpi/tftp. I'm guessing folder ownership is a consideration. It's annoying if you want to stfp/scp files off the WAN Pi and the folder is owned by root, so you cannot pull the files off with the wlanpi user account.

I think any folder used should at least allow the wlanpi user (or its group) read/write access to the folder used to receive files. Must admit the /home/wlanpi/tftp option does sound more attractive the more I think about it. @jolla @jiribrejcha any thoughts?

**Comment by jiribrejcha** [comment]
If read&write access works for the "wlanpi" user in the default location "/srv/tftp", I suggest we use this one.

It might be useful if we exposed the TFTP directory via the new web GUI so that users could upload or download files from the WLAN Pi's TFTP folder using a browser on their iPad/Android device. I am guessing we might run into some permission issues then if its in the /svt/tftp directory?

**Comment by jolla** [comment]
I agree with @jiribrejcha, the dir needs to be writable from the wlanpi user account, as long as that works I'm good with using the default dir.

**Comment by danielmundi** [comment]
I set up the default folder `/srv/tftp` owned by root and group 'tftp', then added wlanpi user to this group and set the permissions to allow the group write permissions.
So any user on 'tftp' group can seamlessly read and write to this directory.

In summary, wlanpi user can read and write from the default location.

The image I just published on the group already has this configuration, please try it and let me know if you find any issues.

**Comment by jiribrejcha** [comment]
Added to the v2 image
