### ISSUE TITLE
AAP125 - TFTP - Test TFTP Server

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#75]

**Comment by wifinigel** [comment]
Tests performed:

test rig:

1. Silver WLAN Pi
2. Image Armbian_20.08.0-trunk_Wlanpi-neo2_buster_current_5.4.49.img.gz
3. WLAN Pi ethernet port connected to Cisco 3650 1gbps port
4. Windows laptop connected to Cisco 3650 1gbps port

Tests performed from fresh boot:

1. Created test file /srv/tftp/test.txt on WLAN Pi via SSH session & nano editor
2. Used TFTPd64 TFTP client/server program on Windows laptop (used as client)
3. File pulled Ok from WLAN Pi to Windows laptop(settings below):

![image](https://user-images.githubusercontent.com/19818404/86407357-cee91500-bcac-11ea-9892-995330bab7ee.png)

4. /srv/tftp/test.txt file removed from WLAN Pi (so /srv/tftp dir now empty)

5. Attempted to upload files from Windows laptop to WLAN Pi, but TFTP transfer failed. Only way to get around the failure was to create an empty file on the WLAN Pi and chmod 777 the file. This is a permissions issue with the TFTP server, but am unsure what permissions we actually need - is it a security issue to allow open TFTP upload of files?

@jiribrejcha @jolla @danielmundi What are your thoughts please - I'm not sure what the original intent of adding the TFTP server was.

**Comment by jiribrejcha** [comment]
I think we need RW access to TFTP to use it to its full potential.

If we only allow TFTP server in the server mode or manually by starting its service it should not cause any harm. Perhaps we don't give files the executable flag (so that scripts cannot be ran from the TFTP folder)?

Worst case someone could do denial of service by filling up all storage space of the Pi.

**Comment by jiribrejcha** [comment]
I’ve just tested read and write access to the TFTP server from a Cisco 3560CX switch. These changes are required to make it work.

1. Change permissions (mandatory, it doesn’t work without this)
`sudo chmod -R 777 /srv/tftp
`
2. Edit config file:
`sudo nano /etc/default/tftpd-hpa
`
3. Use IPv4 and enable TFTP clients saving files to TFTP (--create):
`TFTP_OPTIONS="--secure --ipv4 --create"
`
4. Restart the service if you want to see it in action immediately:
`sudo systemctl restart tftpd-hpa.service`

**Comment by wifinigel** [comment]
Thanks @jiribrejcha 

@danielmundi can we add these updates to the build please?

**Comment by jiribrejcha** [comment]
Added by Daniel to the latest dev v2 image. Read and write access are working as expected.
