### ISSUE TITLE
BIB33 - Disable NetworkManager service in base build

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#79]
NetworkManager has caused some operational issues for wlan0 during mode switching. Disabling the NM service mitigates the issue. Please disable the service in the base build.

**Comment by danielmundi** [comment]
Services disabled:

```
systemctl disable NetworkManager.service
systemctl disable NetworkManager-wait-online.service
systemctl disable NetworkManager-dispatcher.service
systemctl disable network-manager.service
```

**Comment by jiribrejcha** [comment]
NetworkManager re-enabled only for Ethernet interfaces and it now compatible with the v2 image including Hotspot and latest build of Wi-Fi Console.

**Comment by jiribrejcha** [comment]
Change of direction - we decided to disable NetworkManager completely and not to use it anymore

@danielmundi, can you please re-apply these changes to the v2 image?

```
systemctl disable NetworkManager.service
systemctl disable NetworkManager-wait-online.service
systemctl disable NetworkManager-dispatcher.service
systemctl disable network-manager.service

```

**Comment by jiribrejcha** [comment]
The goal is for eth0 DHCP client leases to be available in /var/lib/dhcp/dhclient.eth0.leases for FPMS and other scripts

**Comment by jiribrejcha** [comment]
NM removed from the image completely by Daniel
eth0 section uncommented in Classic mode already
Uncommented eth0 section in Hotspot and wconsole modes and awaiting PR approval to dev

**Comment by jiribrejcha** [comment]
NM completely removed from v2 image by Daniel
