### ISSUE TITLE
AAP145 - test avahi in base build

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#81]
Verify name resolution of wlanpi.local over OTG

**Comment by jiribrejcha** [comment]
Verified on the latest Armbian_20.08.0-trunk_Wlanpi-neo2_buster_current_5.4.49.img

![image](https://user-images.githubusercontent.com/18701525/86410489-bbd94380-bcb2-11ea-8bba-4977d84e01b2.png)
