### ISSUE TITLE
NetworkManager requirement - remove all references to eth0 from /etc/network/interfaces

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/v2-migration-docs#88]
If we keep eth0 config in /etc/network/interfaces, there will be conflicts and eth0 will get 2 dynamic IP addresses assigned to eth0.

Removing eth0 from /etc/network/interfaces fixes this. Remove from **ALL WLAN Pi MODES**.

![Screenshot 2020-07-15 at 23 16 34](https://user-images.githubusercontent.com/18701525/87605769-5abd6100-c6f1-11ea-81ea-f4f86aabfd3c.png)

**Comment by jiribrejcha** [comment]
Suggested new content of /etc/network/interfaces:

```
#WLAN Pi now uses NetworkManager to manage eth0, eth0 section has to be commented out here to prevent 2 IPs from being assigned to eth0 and other conflicts
# Default eth0 as DHCP
#allow-hotplug eth0
#iface eth0 inet dhcp
```

**Comment by wifinigel** [comment]
@jiribrejcha I'll need to re-test wiperf, as it uses an eth0 config in this file.

**Comment by wifinigel** [comment]
@jiribrejcha wconsole & hotspot also will need cfg files modifying & retesting as  their interfaces file uses an eth0 entry

**Comment by jiribrejcha** [comment]
@wifinigel I've tested wconsole and hotspot now. Both are working fine after commenting eth0 config out in /etc/network/interfaces.

**Comment by jiribrejcha** [comment]
Tested and did pull requests to:
- wconsole dev
- wlanpihotspot v2_image

@danielmundi could you please update /etc/network/interfaces in the base image and comment out the eth0 section, please? This is to allow NetworkManager properly manage eth0 without conflicts.

Suggested eth0 section content in /etc/network/interfaces after this change:

#WLAN Pi now uses NetworkManager to manage eth0, eth0 section has to be commented out here to prevent 2 IPs from being assigned to eth0 and other conflicts
# Wired ethernet
#auto eth0
#iface eth0 inet dhcp

**Comment by jiribrejcha** [comment]
Change of direction - we are disabling NetworkManager completely on the WLAN Pi v2 now
